# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

name: base
description: "base-lib."

version: 0.0.1

publish_to: "none"

environment:
  sdk: ^3.5.0

dependencies:
  characters: ^1.2.1
  http: ^1.2.0

  stdlibc: ^0.1.4

  image: ^4.1.3
  sqlite3: ^2.1.0


  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  path_provider: ^2.1.3

  flutter_animate: ^4.5.0

#  bootstrap_icons: ^1.10.2+1
#  cyclop: ^0.6.0
#  carousel_slider: ^4.2.1
#  smooth_page_indicator: ^1.0.1 # "Scrolling dots" effect, with `carousel_slider`


flutter:

  uses-material-design: true

#  assets:
#    - images/a_dot_burr.jpeg
#    - images/a_dot_ham.jpeg
#  fonts:
#    - family: Schyler
#      fonts:
#        - asset: fonts/Schyler-Regular.ttf
#        - asset: fonts/Schyler-Bold.ttf
#          weight: 700
#        - asset: fonts/Schyler-Italic.ttf
#          style: italic
